### ISSUE TITLE
IORedis Cluster duplicate method missing

### ISSUE THREAD

**Issue by marektihkan** [SGrondin/bottleneck#129]
When creating a cluster connection using ioredis and passing the client to IORedisConnection it fails with duplicate method error.

**Code:**
```
const Redis = require('ioredis')
const Bottleneck = require('bottleneck')

const client = new Redis.Cluster(process.env.REDIS_CLUSTER_HOSTS)
const connection = new Bottleneck.IORedisConnection({ client })
const group = new Bottleneck.Group({ connection })
```

**Error:**
```
TypeError: this.client.duplicate is not a function
     at new IORedisConnection (/usr/src/app/node_modules/bottleneck/lib/IORedisConnection.js:42:39)
     at Object.<anonymous> (/usr/src/app/lib/rate-limits/group.js:5:20)
     at Module._compile (internal/modules/cjs/loader.js:689:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
     at Module.load (internal/modules/cjs/loader.js:599:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
     at Module.require (internal/modules/cjs/loader.js:637:17)
     at require (internal/modules/cjs/helpers.js:22:18)
     at Object.<anonymous> (/usr/src/app/rpc/request.js:4:19)
     at Module._compile (internal/modules/cjs/loader.js:689:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
     at Module.load (internal/modules/cjs/loader.js:599:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
     at Module.require (internal/modules/cjs/loader.js:637:17)
```

At the moment I found workaround by adding the duplicate method to `Redis.Cluster` class
```
Redis.Cluster.prototype.duplicate = function () {
  return new Redis.Cluster(this.startupNodes, this.options)
}
```

**Comment by SGrondin** [comment]
Nice catch. This is happening due to the combination of using Redis Cluster and a custom connection. I've just pushed a fix (and a test), I'll release it in a few hours.

**Comment by SGrondin** [comment]
Fixed in [v2.19.2](https://github.com/SGrondin/bottleneck/releases/tag/v2.19.2) 🎉 Thank you for the little workaround snippet, it made it very quick and easy to fix.

**Comment by marektihkan** [comment]
Thanks for the quick fix.

It seems that `startupNodes` and `options` are marked as private in IORedis library. It is using TypeScript and it doesn't affect at the moment, but when JavaScript starts to support private fields in classes then all hell breaks loose. The best option might be to ask IORedis library maintainers to add the duplicate method to that class.

**Comment by SGrondin** [comment]
Yes, absolutely and without version pinning it's vulnerable to a rename on their side. I've created this issue: https://github.com/luin/ioredis/issues/921

**Comment by SGrondin** [comment]
Here's the PR: https://github.com/luin/ioredis/pull/926. Bottleneck won't break and won't need any update once ioredis releases the fix.

**Comment by SGrondin** [comment]
...and it's in ioredis `4.12.0`! 🎉
