### ISSUE TITLE
ReplyError: ERR Error running script (call to f_9681e2eb0f886df26fa948812dbd55b6263256c4): @user_script:157: user_script:157: too many results to unpack

### ISSUE THREAD

**Issue by matomesc** [SGrondin/bottleneck#151]
**Versions**
redis server@4.0.14
node@12.16.1
bottleneck@2.19.5
ioredis@4.14.0

I'm getting the following error when running a limiter under heavy load without `highWater` config set:

```
{
  "command": {
    "name": "evalsha",
    "args": [
      "9681e2eb0f886df26fa948812dbd55b6263256c4",
      "8",
      "b_my-limiter_settings",
      "b_my-limiter_job_weights",
      "b_my-limiter_job_expirations",
      "b_my-limiter_job_clients",
      "b_my-limiter_client_running",
      "b_my-limiter_client_num_queued",
      "b_my-limiter_client_last_registered",
      "b_my-limiter_client_last_seen",
      "1584463898439",
      "pakqh4wntyn",
      "0",
      "2.19.5",
      "maxConcurrent",
      "5",
      "minTime",
      "250",
      "highWater",
      "",
      "strategy",
      "1",
      "penalty",
      "",
      "reservoir",
      "40",
      "reservoirRefreshInterval",
      "",
      "reservoirRefreshAmount",
      "",
      "reservoirIncreaseInterval",
      "1000",
      "reservoirIncreaseAmount",
      "2",
      "reservoirIncreaseMaximum",
      "40",
      "id",
      "my-limiter",
      "version",
      "2.19.5",
      "groupTimeout",
      "",
      "clientTimeout",
      "10000"
    ]
  },
  "msg": "Unhandled Promise Rejection",
  "stack": "ReplyError: ERR Error running script (call to f_9681e2eb0f886df26fa948812dbd55b6263256c4): @user_script:157: user_script:157: too many results to unpack \n    at parseError (/app/server/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/app/server/node_modules/redis-parser/lib/parser.js:302:14)",
  "type": "Error"
}
```

**Comment by colin-oos** [comment]
^ I am getting this same exact error too

**Comment by dobrynin** [comment]
same

**Comment by dobrynin** [comment]
FYI I think this can happen if you don't set a timeout on your limiters. We create limiters in AWS Lambda and eventually ran into this because the limiters never expired.
