### ISSUE TITLE
redis clustered (elasticache) - crossslot issue

### ISSUE THREAD

**Issue by RichardWright** [SGrondin/bottleneck#180]
Hi!

We deployed bottleneck and recently migrated to a new elasticache setup, using redis with 'cluster mode' enabled. Once we migrated we started getting crossslot errors

`"ReplyError: CROSSSLOT Keys in request don't hash to the same slot\n at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)\n at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)"`

Is there a specific way we need to configure keys or does bottleneck not use hash tags on the keys?

Thanks!

**Comment by hr12408** [comment]
I am having this same issue did you end up figuring this out?

**Comment by RichardWright** [comment]
Nope, we gave up and didn't use cluster mode.

**Comment by mortiy** [comment]
In cluster mode all your transactions can operate only on keys with same hash slot.
To force same hash slot you should specify which part of limiter ID is used for that hash surrounding it with `curly braces`.
Like so:
```javascript 
new Bottleneck({
     id: "limiter-{myId}"
})
```

More details: https://redis.com/blog/redis-clustering-best-practices-with-keys/

**Comment by yarinvak** [comment]
> In cluster mode all your transactions can operate only on keys with same hash slot. To force same hash slot you should specify which part of limiter ID is used for that hash surrounding it with `curly braces`. Like so:
> 
> ```js
> new Bottleneck({
>      id: "limiter-{myId}"
> })
> ```
> 
> More details: https://redis.com/blog/redis-clustering-best-practices-with-keys/

Had this too - your suggestion seems to fix it, thanks @mortiy

**Comment by bhaskar-pv** [comment]
Still getting same issue even if I have passed `id`

ReplyError: CROSSSLOT Keys in request don't hash to the same slot.

```
{
  maxConcurrent: 1,
  minTime: 333,
  id: 'limiter-for-google-{clientId}',
  datastore: 'ioredis',
  clientOptions: 'rediss://{elasticachename}.amazonaws.com:6379'
}
```

I run 10 lambda in parallel and get this. Not sure what is the problem here.
