### ISSUE TITLE
ReplyError: ERR SETTINGS_KEY_NOT_FOUND when use in Clustering mode with Redis 7.x

### ISSUE THREAD

**Issue by Pierre-Gilles** [SGrondin/bottleneck#205]
Hi! 

First, thank you for this great library 🙂

I tried running this library in Cluster mode with Redis 7.x, and I got the following error:

```
ReplyError: ERR SETTINGS_KEY_NOT_FOUND
 command: 'EVALSHA',
  args: [
    'f00a66a4159e8488fd6e3b8ccba92a8c602f2062',
    8,
    'b_gladys-gateway_settings',
    'b_gladys-gateway_job_weights',
    'b_gladys-gateway_job_expirations',
    'b_gladys-gateway_job_clients',
    'b_gladys-gateway_client_running',
    'b_gladys-gateway_client_num_queued',
    'b_gladys-gateway_client_last_registered',
    'b_gladys-gateway_client_last_seen',
    1662654440828,
    '4gydkiwu33',
    '0',
    '1'
  ],
  code: 'ERR'
}
```

If I use an older version of Redis, it works fine.

Any idea of what changed with this version of Redis ?

**Comment by mfrye** [comment]
Just ran into this as well

**Comment by menbatisiunissart** [comment]
same issue here as well

**Comment by avermeil** [comment]
Getting this same error as well:

```
ReplyError: ERR SETTINGS_KEY_NOT_FOUND
    at parseError (/usr/api/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/api/node_modules/redis-parser/lib/parser.js:302:14) {
  command: 'EVALSHA',
  args: [
    '8bd3e064b718321194a8df49c69e48fd0ffb4dcd',
    8,
    'b_builtwith_throttler_settings',
    'b_builtwith_throttler_job_weights',
    'b_builtwith_throttler_job_expirations',
    'b_builtwith_throttler_job_clients',
    'b_builtwith_throttler_client_running',
    'b_builtwith_throttler_client_num_queued',
    'b_builtwith_throttler_client_last_registered',
    'b_builtwith_throttler_client_last_seen',
    1665586647495,
    'b9zz33fpice'
  ],
  code: 'ERR'
}
```

**Comment by yarinvak** [comment]
We're also experiencing it with `bitnami/redis:7.0.4-debian-11-r4`, any workaround? @SGrondin

**Comment by ricardofrancoli** [comment]
Same here:
```
ReplyError: ERR SETTINGS_KEY_NOT_FOUND
  command: 'EVALSHA',
  args: [
    '8bd3e064b718321194a8df49c69e48fd0ffb4dcd',
    8,
    'b_awql_throttler_settings',
    'b_awql_throttler_job_weights',
    'b_awql_throttler_job_expirations',
    'b_awql_throttler_job_clients',
    'b_awql_throttler_client_running',
    'b_awql_throttler_client_num_queued',
    'b_awql_throttler_client_last_registered',
    'b_awql_throttler_client_last_seen',
    1665734323793,
    '0efrswlefrmj'
  ],
  code: 'ERR'
}
```

**Comment by nlopez99** [comment]
We're experiencing this on an elasticache redis instance running 6.2.6, any updates on this? @SGrondin

**Comment by HelloKashif** [comment]
It's probably happening because of the heartbeat check which validates that keys exist on redis. But since Groups timeout kills the limiter after timeout those keys don't exist anymore.
https://github.com/SGrondin/bottleneck/blob/b83528333ba4d27cf70b81cc2be12e09d7ff692f/src/Scripts.coffee#L84

The error usually goes away once the `group_check.lua` runs so a quick hack would be ignore the error for a while until it goes away

**Comment by dobrynin** [comment]
Also ran into this. Between this issue and ETIMEDOUT errors, it's been very difficult to get ioredis cleanly working w/ ElastiCache 😢

**Comment by luisvnw** [comment]
Also experiencing this

**Comment by cuzzlor** [comment]
Also this

**Comment by luisvnw** [comment]
Had to use some fork of @maselious/bottleneck

**Comment by mfrye** [comment]
Crazy that I'm still getting alerts on this and it hasn't been fixed in almost 3 years. Pretty sure this project is dead.

Unfortunately we haven't found a good alternative for node.js elsewhere yet. So we've been stuck using this and on an old version of Elasticache. With that said, I wonder if Cursor could work to convert the whole project into non coffee code and fix the bug here.

**Comment by luisvnw** [comment]
@mfrye True, there is no alternative to this, it's a shame. The fork I mentioned does work but same problem as this one, it's not maintained. I guess we should do it

**Comment by sderrow** [comment]
I [fixed](https://github.com/sderrow/bottleneck/commit/e479267fe5120db0432652c31753dc9e16969be8) this particular bug in my fork as well. Since this package doesn't seem to be maintained anymore, I [published](https://www.npmjs.com/package/@sderrow/bottleneck) my version to npm. It also fixes a couple other things too and I'm working on a [rewrite](https://github.com/sderrow/bottleneck/pull/5) in modern JS (and eventually typescript) since coffeescript isn't needed anymore.
