### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by reggi** [SGrondin/bottleneck#27]
Hey, any idea why this isn't working correctly?

```js
import Promise from 'bluebird'
import Bottleneck from 'bottleneck'

const limiter = new Bottleneck(1, 100)
const example = (v) => Promise.delay(100).then(() => v)
const exampleLimited = (...args) => limiter.schedule.apply(null, [example, ...args])
```

**Comment by reggi** [comment]
```
/Users/thomas/Desktop/wonder/node_modules/bottleneck/lib/Bottleneck.js:229
      return this.schedulePriority.apply({}, Array.prototype.concat(MIDDLE_PRIORITY, args));
                                  ^

TypeError: Cannot read property 'apply' of undefined
    at Bottleneck.schedule (/Users/thomas/Desktop/wonder/node_modules/bottleneck/lib/Bottleneck.js:229:35)
    at exampleLimited (/Users/thomas/Desktop/wonder/src/test-simple-rate-limiter/test.js:8:54)
    at Object.<anonymous> (/Users/thomas/Desktop/wonder/src/test-simple-rate-limiter/test.js:10:1)
    at Module._compile (module.js:571:32)
    at loader (/Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at /Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/babel-cli/lib/_babel-node.js:159:24
    at Object.<anonymous> (/Users/thomas/.nvm/versions/node/v7.2.1/lib/node_modules/babel-cli/lib/_babel-node.js:160:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by SGrondin** [comment]
Yes, if you read [the docs of apply()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) you'll see that the first argument is the `this` inside the invoked function. What happens is that you pass `null`, so JS creates an empty `this` and Bottleneck tries to call `this.schedulePriority` but it's missing, which causes the exception you see. You need to be careful if you choose to use `apply`/`call`/`bind`!!!

Try this:
```js
const exampleLimited = (...args) => limiter.schedule.apply(limiter, [example, ...args])
```
